# Generated by Django 5.1.1 on 2024-09-18 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['animal_name']},
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_breed',
            field=models.ManyToManyField(null=True, to='api.animalbreed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_color',
            field=models.ManyToManyField(null=True, to='api.animalcolor'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
