# Generated by Django 5.1.1 on 2024-09-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_animal_options_alter_animal_animal_breed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='animal_breed',
            field=models.ManyToManyField(to='api.animalbreed'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_color',
            field=models.ManyToManyField(to='api.animalcolor'),
        ),
    ]
